version: '3.4'

services:
  helloworldreact:
    image: helloworldreact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
